Presidio action
insightsengineering/r.pkg.template pull request #54
Opened 2022-02-14 11:21 UTC by tomszosz

new action type

2022-02-14 12:27 UTC, dinakar29 requested changes

2022-02-14 12:27 UTC, dinakar29 commented on .github/workflows/presidio.yaml
> +name: Presidio 🧪
```suggestion
name: PII Check 💳
```

2022-02-14 12:27 UTC, dinakar29 commented on .github/workflows/presidio.yaml
> +    if: "! contains(github.event.commits[0].message, '[skip presidio]')"
```suggestion
    if: "! contains(github.event.commits[0].message, '[skip pii]')"
```

2022-02-14 14:37 UTC, dinakar29 commented
@tomszosz Please pull in the latest changes from the `main` branch into this branch

2022-02-14 14:38 UTC, dinakar29 commented
Also, I'm going to update the Presidio action so that its output is more meaningful, maybe even add annotation capabilities.

2022-02-16 07:11 UTC, tomszosz commented
> @tomszosz Please pull in the latest changes from the `main` branch into this branch

latest changes from `main` branch are included

2022-02-21 19:11 UTC, dinakar29 approved these changes

2022-02-21 19:11 UTC, dinakar29 commented on .github/workflows/gitleaks.yaml
> +
```suggestion
```

2022-02-21 19:23 UTC, merged